# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hemanth kumar/soc_project_final/soc_project_final.srcs/sources_1/bd/object_detection/ip/object_detection_processing_system7_0_0/object_detection_processing_system7_0_0.xci
# IP: The module: 'object_detection_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hemanth kumar/soc_project_final/soc_project_final.gen/sources_1/bd/object_detection/ip/object_detection_processing_system7_0_0/object_detection_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'object_detection_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/hemanth kumar/soc_project_final/soc_project_final.srcs/sources_1/bd/object_detection/ip/object_detection_processing_system7_0_0/object_detection_processing_system7_0_0.xci
# IP: The module: 'object_detection_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hemanth kumar/soc_project_final/soc_project_final.gen/sources_1/bd/object_detection/ip/object_detection_processing_system7_0_0/object_detection_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'object_detection_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
