# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/object_detection/object_detection.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==object_detection || ORIG_REF_NAME==object_detection} -quiet] -quiet

# IP: bd/object_detection/ip/object_detection_processing_system7_0_0/object_detection_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==object_detection_processing_system7_0_0 || ORIG_REF_NAME==object_detection_processing_system7_0_0} -quiet] -quiet

# IP: bd/object_detection/ip/object_detection_rst_ps7_0_100M_0/object_detection_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==object_detection_rst_ps7_0_100M_0 || ORIG_REF_NAME==object_detection_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/object_detection/ip/object_detection_axi_dma_0_0/object_detection_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==object_detection_axi_dma_0_0 || ORIG_REF_NAME==object_detection_axi_dma_0_0} -quiet] -quiet

# IP: bd/object_detection/ip/object_detection_axi_smc_ctrl_0/object_detection_axi_smc_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==object_detection_axi_smc_ctrl_0 || ORIG_REF_NAME==object_detection_axi_smc_ctrl_0} -quiet] -quiet

# IP: bd/object_detection/ip/object_detection_axi_smc_mem_0/object_detection_axi_smc_mem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==object_detection_axi_smc_mem_0 || ORIG_REF_NAME==object_detection_axi_smc_mem_0} -quiet] -quiet

# IP: bd/object_detection/ip/object_detection_axis_data_fifo_0_0/object_detection_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==object_detection_axis_data_fifo_0_0 || ORIG_REF_NAME==object_detection_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/object_detection/ip/object_detection_axi_intc_0_0/object_detection_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==object_detection_axi_intc_0_0 || ORIG_REF_NAME==object_detection_axi_intc_0_0} -quiet] -quiet

# XDC: c:/Users/hemanth kumar/soc_project_final/soc_project_final.gen/sources_1/bd/object_detection/object_detection_ooc.xdc
